# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 422)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 10, 391, 311))
        self.frame.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(4)
        self.frame.setObjectName("frame")
        self.labelCam = QtWidgets.QLabel(self.frame)
        self.labelCam.setGeometry(QtCore.QRect(0, 0, 391, 311))
        self.labelCam.setText("")
        self.labelCam.setScaledContents(True)
        self.labelCam.setObjectName("labelCam")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(70, 340, 131, 51))
        self.startButton.setObjectName("startButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 10, 151, 20))
        self.label.setObjectName("label")
        self.assignFist = QtWidgets.QPushButton(self.centralwidget)
        self.assignFist.setGeometry(QtCore.QRect(460, 40, 131, 31))
        self.assignFist.setObjectName("assignFist")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(250, 340, 131, 51))
        self.stopButton.setObjectName("stopButton")
        self.assignPalmC = QtWidgets.QPushButton(self.centralwidget)
        self.assignPalmC.setGeometry(QtCore.QRect(460, 90, 131, 31))
        self.assignPalmC.setObjectName("assignPalmC")
        self.assignPalmO = QtWidgets.QPushButton(self.centralwidget)
        self.assignPalmO.setGeometry(QtCore.QRect(460, 140, 131, 31))
        self.assignPalmO.setObjectName("assignPalmO")
        self.assignThumbsU = QtWidgets.QPushButton(self.centralwidget)
        self.assignThumbsU.setGeometry(QtCore.QRect(460, 190, 131, 31))
        self.assignThumbsU.setObjectName("assignThumbsU")
        self.assignThumbsD = QtWidgets.QPushButton(self.centralwidget)
        self.assignThumbsD.setGeometry(QtCore.QRect(460, 240, 131, 31))
        self.assignThumbsD.setObjectName("assignThumbsD")
        self.actionPalmC = QtWidgets.QLabel(self.centralwidget)
        self.actionPalmC.setGeometry(QtCore.QRect(600, 90, 81, 31))
        self.actionPalmC.setObjectName("actionPalmC")
        self.actionFist = QtWidgets.QLabel(self.centralwidget)
        self.actionFist.setGeometry(QtCore.QRect(600, 40, 81, 31))
        self.actionFist.setObjectName("actionFist")
        self.actionPalmO = QtWidgets.QLabel(self.centralwidget)
        self.actionPalmO.setGeometry(QtCore.QRect(600, 140, 81, 31))
        self.actionPalmO.setObjectName("actionPalmO")
        self.actionThumbsU = QtWidgets.QLabel(self.centralwidget)
        self.actionThumbsU.setGeometry(QtCore.QRect(600, 190, 81, 31))
        self.actionThumbsU.setObjectName("actionThumbsU")
        self.actionThumbsD = QtWidgets.QLabel(self.centralwidget)
        self.actionThumbsD.setGeometry(QtCore.QRect(600, 240, 81, 31))
        self.actionThumbsD.setObjectName("actionThumbsD")
        self.assignDaddyF = QtWidgets.QPushButton(self.centralwidget)
        self.assignDaddyF.setGeometry(QtCore.QRect(460, 290, 131, 31))
        self.assignDaddyF.setObjectName("assignDaddyF")
        self.actionDaddyF = QtWidgets.QLabel(self.centralwidget)
        self.actionDaddyF.setGeometry(QtCore.QRect(600, 290, 81, 31))
        self.actionDaddyF.setObjectName("actionDaddyF")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestia"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Detection: Nothing"))
        self.assignFist.setText(_translate("MainWindow", "Fist"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.assignPalmC.setText(_translate("MainWindow", "Palm_close"))
        self.assignPalmO.setText(_translate("MainWindow", "Palm_open"))
        self.assignThumbsU.setText(_translate("MainWindow", "Thumbs_up"))
        self.assignThumbsD.setText(_translate("MainWindow", "Thumbs_down"))
        self.actionPalmC.setText(_translate("MainWindow", ""))
        self.actionFist.setText(_translate("MainWindow", ""))
        self.actionPalmO.setText(_translate("MainWindow", ""))
        self.actionThumbsU.setText(_translate("MainWindow", ""))
        self.actionThumbsD.setText(_translate("MainWindow", ""))
        self.assignDaddyF.setText(_translate("MainWindow", "Daddy_finger"))
        self.actionDaddyF.setText(_translate("MainWindow", ""))
